# # # # # # # # # # # # # # # # # # #
# Pancake's official nginx config.
# # # # # # # # # # # # # # # # # # #
#
# 1. This conf file passes things to PHP via fastcgi, running on port 9000.
# If you do things differently in your server, you need to edit this.
#
# 2. Edit "/path/to/pancake" so it matches your Pancake's directory.
#
# 3. Edit "billing.yourdomain.com" to match whatever subdomain you
# want to run Pancake on.
#
# 4. Pancake will, by default, keep adding "index.php" to its
# links because it doesn't know that you have URL rewriting on.
# To fix this, go to system/pancake/config/config.php and look for the following:
#
# $config['index_page'] = 'index.php';
#
# Replace it with:
#
# $config['index_page'] = '';
#
# That's it, we're just removing the "index.php" and leaving that empty.
#
# And that's all you need; your Pancake should run flawlessly now.
#
# If you any problems at all, please start a support ticket at:
# https://www.pancakeapp.com/account/support/ticket/new
#
# # # # # # # # # # # # # # # # # # #

server {
    root /path/to/pancake;
    listen 80;
    server_name billing.yourdomain.com;
    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ @router;
        index index.html index.php;
        error_page 403 = @router;
        error_page 404 = @router;
    }

    location ~ (.php|\/[^./]+)$ {
        rewrite ^(.*)$ /index.php break;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param HTTP_PROXY "";
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location @router {
        rewrite ^(.*)$ /index.php break;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param HTTP_PROXY "";
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    } 
}