// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For migrations, prefer DIRECT_DATABASE_URL (Supabase direct connection or session pooler).
    // If unset, falls back to DATABASE_URL.
    // Transaction-pooler URLs (port 6543) do NOT support DDL — use direct/session pooler here.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
